### PR TITLE
Make more functions type stable

### PR DESCRIPTION
**Pull request by sharanry**
With https://github.com/JuliaMath/HCubature.jl/pull/43 solves part of https://github.com/SciML/Integrals.jl/issues/65

Summary: Use Val to dispatch transformation_if_inf differently based on solver kwarg

CC: @ChrisRackauckas

### CODE REVIEW

**Comment by sharanry** [comment]
@ChrisRackauckas 

- This still does not solve the larger issue of making `HCubatureJL` type stable. See https://github.com/JuliaMath/HCubature.jl/issues/42

**Comment by sharanry** [comment]
@ChrisRackauckas Use of forward diff [here](https://github.com/SciML/Integrals.jl/blob/master/src/Integrals.jl#L82) makes this function inherently type unstable. We anyway plan to remove its usage in the near future?

**Comment by ChrisRackauckas** [comment]
How would that be replaced? I think we do need the determinant of the Jacobian? We can just add some autodiff options to control the chunksize and such. Since that call is repeated, we should create a config and reuse the config each call.

**Comment by sharanry** [comment]
> How would that be replaced? I think we do need the determinant of the Jacobian?

The computation of jacobian is type unstable. If we use something other than forward diff, couldn't that be potentially solved?

**Comment by ChrisRackauckas** [comment]
The issue is just the chunk size choice in ForwardDiff. If you allow the same autodiff options as the stiff differential equation solvers (autodiff = true/false, Val{true}/Val{false}, chunksize = Val{0}) then it would be fine. But yes, regardless of that we should have a FiniteDiff option just for compatibility.

**Pull request merged**
